all:
	python kamek.py project.yaml
#	head -n 16 mount/riivolution/test.template > mount/riivolution/test.xml
#	cat build/ntsc_riiv.xml >> mount/riivolution/test.xml
#	tail -n 2 mount/riivolution/test.template >> mount/riivolution/test.xml

