all:
	@make -f Makefile.rawk
	@make -f Makefile.rii
	@make -f Makefile.zero4
rawk:
	@make -f Makefile.rawk
rii:
	@make -f Makefile.rii
zero4:
	@make -f Makefile.zero4	
clean:
	@make -f Makefile.rawk clean
	@make -f Makefile.rii clean
	@make -f Makefile.zero4 clean
